config/routes.rb
Rails.application.routes.draw do

  resources :relationships, only: [:create, :destroy]
  resources :posts  
  resources :tags, only: [:create, :new, :index, :show, :destroy]

  
  root 'pages#home'
  get '/explore' => 'tags#index'
  get '/add_post' => 'posts#new'
  get '/profile/:id' => 'pages#profile', as: 'user' # override default routes.
  get 'auth/:provider/callback', to: "sessions#create"
  delete "sign_out", to: "sessions#destroy", as: 'sign_out'

end

app/views/layouts/_nav.html.erb
<!-- we will render seperate nav bars depending on if the user is signed in or not. -->
<% if current_user %>
  <%= render '/layouts/nav_user' %>
<% else %>
  <%= render '/layouts/nav_guest' %>
<% end %>

app/views/layouts/_nav_guest.html.erb
<!-- Navbar for users who haven't logged in -->
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <img class="navbar-brand" src="/infinity.png">

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Home </a></li>
        <li><a href="/explore">Explore </a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><button type="button" class="btn btn-primary navbar-btn" style="float: right; margin-top: 5%"><%= link_to('Sign In with Facebook', 'auth/facebook', style: "color: white") %></button></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav> 

app/views/layouts/_nav_user.html.erb
<!-- Nav bar for logged in users -->

<a name="top"></a>
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    
    <img class="navbar-brand" src="/infinity.png">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Home </a></li><!--
        <li><a href="/explore">Explore </a></li>-->
        <li><%= link_to("Profile", user_path(current_user)) %></li>
   <!-- <li><a href="/">Notifications </a></li>
        <li><a href="/home">Messages </a></li>-->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <form class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
          </form>
        </li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= image_tag(current_user.profile_image, class: "rounded-img", height: "33px", width: "33px") %>
          
          <ul class="dropdown-menu">
     <!--   <li><a href="/">Settings </a></li>
            <li role="separator" class="divider"></li>-->
            <li><%= link_to('Log Out', sign_out_path, :method => :delete) %></li>
          </ul>
        </li>
        <li><button class="btn btn-primary" type="button" style="float: right; margin-top: 10px;" data-toggle="modal" data-target="#mynewpost">Add Post</button></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IWILLMAKETHAT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render '/layouts/nav' %>
	<div class="container">
	  <span class="notice"><%= notice %></span>
	  <span class="alert"><%= alert %></span>
	  <%= yield %>
	</div>
</body>
</html>